<<<<<<< HEAD
ERROR - 2023-01-27 03:20:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#7 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-27 03:20:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
 5 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-27 03:21:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#7 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-27 03:21:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
 5 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-27 03:21:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#7 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-27 03:21:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
 5 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-27 03:21:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#7 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/events_registration_app_with_codeigniter/app/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
#5 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#6 /var/www/events_registration_app_with_codeigniter/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/events_registration_app_with_codeigniter/public/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-27 03:21:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/DashboardController.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\DashboardController->registered()
 5 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
=======
CRITICAL - 2023-01-27 06:16:37 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\Signup.php(14): view('signup', [])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Signup->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-27 07:14:25 --> Invalid file: /auth/login.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth/login.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('/auth/login', [], true)
 3 APPPATH\Controllers\Login.php(13): view('/auth/login')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Login->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-27 07:26:29 --> Invalid file: signup.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('signup.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('signup', [], true)
 3 APPPATH\Controllers\Signup.php(39): view('signup', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Signup->store()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
>>>>>>> e95a1eabe57b51938540f49e53452574544692d0
